# Generated by Django 5.0.4 on 2024-04-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('vendor_code', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0, help_text='Цена за 1 кг')),
                ('left', models.IntegerField(default=1, help_text='Количество оставшегося сыра (кг)')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('secondName', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='List_cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.1)),
                ('id_cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeseFactory.cheese')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeseFactory.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeseFactory.user'),
        ),
    ]
