# Generated by Django 5.0.4 on 2024-04-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_user',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='List_cheese',
        ),
    ]
