# Generated by Django 5.0.4 on 2024-04-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0002_rename_id_user_order_user_delete_list_cheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='vendor_code',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='List_cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.1)),
                ('id_cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeseFactory.cheese')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeseFactory.order')),
            ],
        ),
    ]
