# Generated by Django 5.0.4 on 2024-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0003_alter_cheese_vendor_code_list_cheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='vendor_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
