# Generated by Django 5.0.4 on 2024-04-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0004_alter_cheese_vendor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_cheese',
            old_name='id_cheese',
            new_name='cheese',
        ),
        migrations.RenameField(
            model_name='list_cheese',
            old_name='id_order',
            new_name='order',
        ),
    ]
