# Generated by Django 5.0.4 on 2024-04-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0005_rename_id_cheese_list_cheese_cheese_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='data_order',
        ),
        migrations.AddField(
            model_name='order',
            name='list_cheeses',
            field=models.ManyToManyField(through='cheeseFactory.List_cheese', to='cheeseFactory.cheese'),
        ),
    ]
