# Generated by Django 5.0.4 on 2024-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0006_rename_order_data_order_data_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='list_cheese',
            constraint=models.UniqueConstraint(fields=('order', 'cheese'), name='unique_position'),
        ),
    ]
