# Generated by Django 5.0.4 on 2024-04-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0007_list_cheese_unique_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='description',
            field=models.TextField(default='', help_text='Описание сыра'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, оформивший заказ', on_delete=django.db.models.deletion.CASCADE, to='cheeseFactory.user'),
        ),
    ]
