# Generated by Django 5.0.4 on 2024-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseFactory', '0010_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='left',
            field=models.FloatField(default=1, help_text='Количество оставшегося сыра (кг)'),
        ),
    ]
